//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiRandomNameGenerator.Asset {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiRandomNameGenerator.Asset.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abram
        ///Adamič
        ///Adlešič
        ///Agrež
        ///Ahačič
        ///Ahlin
        ///Ahčan
        ///Ahčin
        ///Ajdič
        ///Ajlec
        ///Aleksič
        ///Aleš
        ///Alešovec
        ///Alič
        ///Aljančič
        ///Aljaž
        ///Alujevič
        ///Ambrož
        ///Ambrožič
        ///Ameršek
        ///Andoljšek
        ///Andolšek
        ///Andreaš
        ///Andrejka
        ///Andrejčič
        ///Andronja
        ///Ankele
        ///Ankerst
        ///Anko
        ///Antič
        ///Antolin
        ///Antolič
        ///Antončič
        ///Anžlovar
        ///Apih
        ///Arh
        ///Arhar
        ///Arigler
        ///Arih
        ///Arko
        ///Arlič
        ///Armič
        ///Arnejc
        ///Arnež
        ///Arnič
        ///Artač
        ///Arzenšek
        ///Arčon
        ///Atelšek
        ///Augustič
        ///Avbelj
        ///Avguštin
        ///Avsec
        ///Avsenek
        ///Avsenik
        ///Avčin
        ///Avšič
        ///Ačko
        ///Ačkun
        ///Aškerc
        ///Ažbe
        ///Ažman
        ///Ažnik
        ///Babič
        ///B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LastNames {
            get {
                return ResourceManager.GetString("LastNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abel
        ///Abraham
        ///Adam
        ///Adem
        ///Adi
        ///Admir
        ///Adnan
        ///Adolf
        ///Adrian
        ///Adriano
        ///Adrijan
        ///Adrijano
        ///Ahac
        ///Ahmed
        ///Ahmet
        ///Ajdin
        ///Al
        ///Alain
        ///Alan
        ///Albert
        ///Alberto
        ///Albin
        ///Albino
        ///Aldin
        ///Aldo
        ///Aleks
        ///Aleksandar
        ///Aleksander
        ///Aleksej
        ///Aleksij
        ///Alen
        ///Alessandro
        ///Alex
        ///Alexander
        ///Alexia
        ///Aleš
        ///Alfi
        ///Alfonz
        ///Alfred
        ///Aljaž
        ///Aljoša
        ///Almir
        ///Alojz
        ///Alojzij
        ///Amadej
        ///Ambrož
        ///Amel
        ///Amir
        ///Anastazij
        ///Andi
        ///Andraž
        ///Andre
        ///Andrea
        ///Andreas
        ///Andrej
        ///Anej
        ///Angel
        ///Ante
        ///Anto
        ///Anton
        ///Antonijo
        ///Antonio
        ///Antun
        ///Anže
        ///Anžej
        ///Arif
        ///Armand
        ///Armand [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Name_Men {
            get {
                return ResourceManager.GetString("Name_Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ada
        ///Adela
        ///Adelajda
        ///Adelina
        ///Admira
        ///Adnana
        ///Adolfa
        ///Adolfina
        ///Adriana
        ///Adrijana
        ///Agata
        ///Agica
        ///Agnes
        ///Ajda
        ///Ajša
        ///Alberta
        ///Albertina
        ///Albina
        ///Albinca
        ///Alda
        ///Aldijana
        ///Aldina
        ///Aleksa
        ///Aleksandra
        ///Alekseja
        ///Aleksija
        ///Aleksina
        ///Alena
        ///Alenka
        ///Alenčica
        ///Alexandra
        ///Aleša
        ///Aleška
        ///Alfonza
        ///Alfreda
        ///Alida
        ///Alijana
        ///Alja
        ///Aljana
        ///Aljoša
        ///Alma
        ///Almira
        ///Alojzija
        ///Amadea
        ///Amadeja
        ///Amalija
        ///Amanda
        ///Amela
        ///Amelija
        ///Amira
        ///Amra
        ///Ana
        ///AnaMarija
        ///Anamarija
        ///Anastazija
        ///Andja
        ///Andrea
        ///Andreja
        ///Andrejka
        ///Andrijana
        ///Anea
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Name_Women {
            get {
                return ResourceManager.GetString("Name_Women", resourceCulture);
            }
        }
    }
}
